name: {{ cookiecutter.project_name }}

dependencies:
  - python=3.10
  - pip
  - pip:
    - -r requirements.txt
    - mlflow==1.26.1
    - typer
    - boto3
    - matplotlib
    - pyarrow
    - sklearn